<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.usoft.framework</groupId>
    <artifactId>usoft-parent</artifactId>
    <version>${revision}${changelist}</version>
  </parent>
  <artifactId>usoft-launcher</artifactId>
  <name>usoft-launcher</name>

  <properties>
    <start-class>com.usoft.framework.launcher.BiApplication</start-class>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-redis</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-cache</artifactId>
    </dependency>
    <dependency>
      <groupId>com.mybatis-flex</groupId>
      <artifactId>mybatis-flex-spring-boot3-starter</artifactId>
      <version>${mybatis.flex.version}</version>
    </dependency>
    <dependency>
      <groupId>com.usoft.framework</groupId>
      <artifactId>usoft-common</artifactId>
      <version>${revision}${changelist}</version>
    </dependency>
    <dependency>
      <groupId>com.usoft.framework</groupId>
      <artifactId>usoft-core</artifactId>
      <version>${revision}${changelist}</version>
    </dependency>
    <dependency>
      <groupId>com.usoft.framework</groupId>
      <artifactId>usoft-security</artifactId>
      <version>${revision}${changelist}</version>
    </dependency>
    <dependency>
      <groupId>com.usoft.framework</groupId>
      <artifactId>usoft-security-thirdauth</artifactId>
      <version>${revision}${changelist}</version>
    </dependency>
    <dependency>
      <groupId>com.usoft.framework</groupId>
      <artifactId>usoft-system</artifactId>
      <version>${revision}${changelist}</version>
    </dependency>
    <dependency>
      <groupId>com.usoft.framework</groupId>
      <artifactId>usoft-ai</artifactId>
      <version>${revision}${changelist}</version>
    </dependency>
    <dependency>
      <groupId>com.usoft.framework</groupId>
      <artifactId>usoft-bi</artifactId>
      <version>${revision}${changelist}</version>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>42.7.4</version>
    </dependency>
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <version>2.3.232</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.mysql</groupId>
      <artifactId>mysql-connector-j</artifactId>
      <version>9.1.0</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>12.8.1.jre11</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>com.oracle.database.jdbc</groupId>
      <artifactId>ojdbc11</artifactId>
      <version>23.4.0.24.05</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <tarLongFileMode>gnu</tarLongFileMode>
          <skipAssembly>false</skipAssembly>
          <archive>
            <manifest>
              <mainClass>${start-class}</mainClass>
            </manifest>
          </archive>
          <descriptors>
            <descriptor>../assembly/build/build.xml</descriptor>
          </descriptors>
        </configuration>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
