spring:
  datasource:
    url: jdbc:h2:mem:usoft_bi;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: ${DB_INIT_MODE:always}
      schema-locations: classpath:db/h2/schema.sql
      data-locations: classpath:db/h2/data.sql

