spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    driver-class-name: oracle.jdbc.OracleDriver
    username: bi
    password: bi
  sql:
    init:
      mode: ${DB_INIT_MODE:always}
      schema-locations: classpath:db/oracle/schema.sql
      data-locations: classpath:db/oracle/data.sql

